/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagementsystem;

import javax.swing.*;

/**
 *
 * @author Giuz
 */
public class RegisterFrame extends javax.swing.JFrame {
    
    private boolean isShown = false;
    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jClearButton = new javax.swing.JButton();
        jGreenButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        showPassBtn = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        showPassBtn1 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(975, 570));
        setResizable(false);
        setSize(new java.awt.Dimension(975, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 40, 20));

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 40, 20));

        jClearButton.setContentAreaFilled(false);
        jClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 100, 30));

        jGreenButton.setContentAreaFilled(false);
        jGreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGreenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jGreenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 100, 30));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Enter Username");
        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField1.setOpaque(true);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 320, 50));

        showPassBtn.setForeground(new java.awt.Color(0, 0, 0));
        showPassBtn.setText("👁");
        showPassBtn.setBorderPainted(false);
        showPassBtn.setContentAreaFilled(false);
        showPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassBtnActionPerformed(evt);
            }
        });
        getContentPane().add(showPassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 40, 30));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("Password");
        jPasswordField1.setToolTipText("");
        jPasswordField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 320, 50));

        showPassBtn1.setForeground(new java.awt.Color(0, 0, 0));
        showPassBtn1.setText("👁");
        showPassBtn1.setBorderPainted(false);
        showPassBtn1.setContentAreaFilled(false);
        showPassBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(showPassBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 40, 30));

        jPasswordField2.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField2.setText("Password");
        jPasswordField2.setToolTipText("");
        jPasswordField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusLost(evt);
            }
        });
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 320, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagementsystem/images/REGISTER.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       MainFrame main = new MainFrame();
       main.setVisible(true);
       main.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginFrame log = new LoginFrame();
        log.setVisible(true);
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearButtonActionPerformed
        jTextField1.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
    }//GEN-LAST:event_jClearButtonActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        if(jTextField1.getText().equals("Enter Username")){
    jTextField1.setText("");
}
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if(jTextField1.getText().isEmpty()){
            jTextField1.setText("Enter Username");
}
    }//GEN-LAST:event_jTextField1FocusLost

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        String pass = String.valueOf(jPasswordField1.getPassword());
    
    if (pass.equals("Password")) {
        jPasswordField1.setText("");
        jPasswordField1.setEchoChar('•'); // Keep the bullets active
    }
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        String pass = String.valueOf(jPasswordField1.getPassword());
    
    if (jPasswordField1.getPassword().length == 0) {
        jPasswordField1.setText("Password");
        jPasswordField1.setEchoChar('•');
        isShown = false; 
    }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jPasswordField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusLost
        String pass = String.valueOf(jPasswordField2.getPassword());
    
    if (pass.isEmpty()) {
        jPasswordField2.setText("Password");
        jPasswordField2.setEchoChar('•'); // FORCE the bullets back on
    }
    }//GEN-LAST:event_jPasswordField2FocusLost

    private void jPasswordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusGained
        String pass = String.valueOf(jPasswordField2.getPassword());
    
    if (String.valueOf(jPasswordField2.getPassword()).equals("Password")) {
        jPasswordField2.setText("");
        jPasswordField2.setEchoChar('•');
    }
    }//GEN-LAST:event_jPasswordField2FocusGained

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void showPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassBtnActionPerformed
        if (!isShown) {
            jPasswordField1.setEchoChar((char)0);
            isShown = true;
        } else {
            jPasswordField1.setEchoChar('•');
            isShown = false;
        }
    }//GEN-LAST:event_showPassBtnActionPerformed

    private void showPassBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassBtn1ActionPerformed
        if (!isShown) {
            jPasswordField2.setEchoChar((char)0);
            isShown = true;
        } else {
            jPasswordField2.setEchoChar('•');
            isShown = false;
        }
    }//GEN-LAST:event_showPassBtn1ActionPerformed

    private void jGreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGreenButtonActionPerformed
        String username = jTextField1.getText();

    String password;
        password = new String(jPasswordField1.getPassword());

    String confirmPassword =    
        new String(jPasswordField2.getPassword());

    if(username.equals("Enter Username") ||
        username.isEmpty() ||

        password.equals("Password") ||
        password.isEmpty() ||

        confirmPassword.equals("Password") ||
        confirmPassword.isEmpty()) {

            JOptionPane.showMessageDialog(this,
                "Please fill in all fields.");

    return;
}


// CHECK PASSWORD MATCH
    if(!password.equals(confirmPassword)) {

        JOptionPane.showMessageDialog(this,
            "Passwords do not match.");

    return;
 }
   
// POPUP ADMIN PASSWORD
    String adminPassword = JOptionPane.showInputDialog(
        this,
        "Enter Admin Password:"
);

// IF CANCELLED
if(adminPassword == null) {
    return;
}

// CHECK ADMIN PASSWORD
if(!adminPassword.equals("admin123")) {

    JOptionPane.showMessageDialog(this,
            "Incorrect Admin Password.");

    return;
}


// SAVE ACCOUNT TEMPORARILY
    Accounts.username = username;
    Accounts.password = password;


    JOptionPane.showMessageDialog(this,
        "Account Registered Successfully!");


// OPEN LOGIN FRAME
    LoginFrame log = new LoginFrame();
    log.setVisible(true);
    log.setLocationRelativeTo(null);


// CLOSE CURRENT FRAME
        this.dispose();
    }//GEN-LAST:event_jGreenButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jClearButton;
    private javax.swing.JButton jGreenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton showPassBtn;
    private javax.swing.JButton showPassBtn1;
    // End of variables declaration//GEN-END:variables
}
