/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SRC;

/**
 *
 * @author reyes
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    private SRC.NewJFrame frame;
    public Login(SRC.NewJFrame frame) {
        
        this.frame = frame;
        initComponents();
        
    }
    
    //fetch and check password
    public void pass(){
        if (password.getText().equals("123")){
            
            frame.setContentPane(new SRC.EMPLOYEE.E_Suites(frame));
            frame.revalidate();
            
        } else if (password.getText().equals("321")){
            
            frame.setContentPane(new SRC.Dashboard(frame));
            frame.revalidate();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        password.setBorder(null);
        add(password);
        password.setBounds(330, 270, 300, 30);

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        add(jButton1);
        jButton1.setBounds(840, 20, 60, 30);

        clear.setBorderPainted(false);
        clear.setContentAreaFilled(false);
        add(clear);
        clear.setBounds(430, 320, 100, 30);

        login.setBorderPainted(false);
        login.setContentAreaFilled(false);
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginKeyPressed(evt);
            }
        });
        add(login);
        login.setBounds(530, 320, 110, 30);

        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        add(jButton4);
        jButton4.setBounds(910, 20, 40, 30);

        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        add(jButton5);
        jButton5.setBounds(780, 20, 60, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/3.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginKeyPressed
       
    }//GEN-LAST:event_loginKeyPressed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
       
    }//GEN-LAST:event_loginMouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       pass();
    }//GEN-LAST:event_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
