/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SRC;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author reyes
 */
public class Register extends javax.swing.JPanel {

    private SRC.NewJFrame frame;
    public Register(SRC.NewJFrame frame) {
        this.frame = frame;
        initComponents();
    }
    
    public void register(String pass, String conpass){
        
        if (!pass.equals(conpass)){
            int warning = JOptionPane.showConfirmDialog(
                    this,
                    "Psssword doesn't match!",
                    "Password Unmatch",
                    JOptionPane.OK_OPTION
            );
            
            if (warning == JOptionPane.OK_OPTION){
                username.setText(null);
                password.setText(null);
                confirm_password.setText(null);
            }
        } else if (pass.equals(conpass)){
             
             
             try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/hms",
                    "root",
                    ""
            );

                 String insert =
                        "INSERT INTO employee (first_name,"
                         + " last_name, account_number,"
                         + " role, status, gender, age,"
                         + " birthdate, email, phone_number) "
                         + " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

                PreparedStatement ps2 = con.prepareStatement(insert);

                ps2.setString(1, username.getText().toString());
                ps2.setString(2, "Reyes");
                ps2.setInt(3, 123123);
                ps2.setString(4, "Employee");
                ps2.setString(5, "Active");
                ps2.setString(6, "Male");
                ps2.setInt(7, 20);
                ps2.setString(8, "August 18, 2005");
                ps2.setString(9, "reyesearnest08182005@gmail.com");
                ps2.setString(10, "09629090803");
                
                
                ps2.executeUpdate();
                ps2.close();
            

            ps2.close();
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

             
            int warning = JOptionPane.showConfirmDialog(
                    this,
                    "User Registered Succesfully!",
                    "User Registered",
                    JOptionPane.OK_OPTION
            );
             
            if (warning == JOptionPane.OK_OPTION){
                username.setText(null);
                password.setText(null);
                confirm_password.setText(null);
            }
        } else {
            System.out.print("La laman");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Register = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        login = new javax.swing.JButton();
        confirm_password = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        P_suites = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        Register.setBorderPainted(false);
        Register.setContentAreaFilled(false);
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        add(Register);
        Register.setBounds(780, 20, 60, 30);

        clear.setBorderPainted(false);
        clear.setContentAreaFilled(false);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        add(clear);
        clear.setBounds(420, 420, 110, 30);

        Home.setBorderPainted(false);
        Home.setContentAreaFilled(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        add(Home);
        Home.setBounds(900, 20, 60, 30);

        username.setBackground(new java.awt.Color(255, 255, 255));
        username.setBorder(null);
        add(username);
        username.setBounds(330, 210, 300, 30);

        confirm.setBorderPainted(false);
        confirm.setContentAreaFilled(false);
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        add(confirm);
        confirm.setBounds(530, 420, 110, 30);

        login.setBorderPainted(false);
        login.setContentAreaFilled(false);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        add(login);
        login.setBounds(840, 20, 70, 30);

        confirm_password.setBackground(new java.awt.Color(255, 255, 255));
        confirm_password.setBorder(null);
        add(confirm_password);
        confirm_password.setBounds(330, 370, 290, 30);

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setBorder(null);
        add(password);
        password.setBounds(330, 290, 290, 30);

        P_suites.setBackground(new java.awt.Color(102, 0, 0));

        jLabel2.setBackground(new java.awt.Color(102, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTER");
        P_suites.add(jLabel2);

        add(P_suites);
        P_suites.setBounds(780, 20, 60, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/REGISTER.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        frame.setContentPane(new Dashboard(frame));
        frame.revalidate();
    }//GEN-LAST:event_HomeActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        frame.setContentPane(new Login(frame));
        frame.revalidate();
    }//GEN-LAST:event_loginActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        frame.setContentPane(new Register(frame));
        frame.revalidate();
    }//GEN-LAST:event_RegisterActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        register(password.getText(), confirm_password.getText());
    }//GEN-LAST:event_confirmActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        username.setText(null);
        password.setText(null);
        confirm_password.setText(null);
    }//GEN-LAST:event_clearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JPanel P_suites;
    private javax.swing.JButton Register;
    private javax.swing.JButton clear;
    private javax.swing.JButton confirm;
    private javax.swing.JPasswordField confirm_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
