/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SRC;

import java.sql.PreparedStatement;
import javax.swing.JPanel;

/**
 *
 * @author reyes
 */
public class RoomInfo extends javax.swing.JPanel {
    private String roomNumber, roomType, details;
    private double rate;
    private JPanel backp;
    private SRC.NewJFrame frame;
    public RoomInfo(SRC.NewJFrame frame, String RN, String roomType, String details, double rate, JPanel backp) {
     
        this.roomType = roomType;
        this.details = details;
        this.rate = rate;
        this.roomNumber = RN;
        this.backp = backp;
        this.frame = frame;
    
        initComponents();
        suite.setText(String.valueOf(roomNumber));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_suites = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        CI = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        birthday = new javax.swing.JTextField();
        residence = new javax.swing.JTextField();
        CO = new javax.swing.JTextField();
        suite = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        proceed = new javax.swing.JButton();
        users = new javax.swing.JButton();
        guests = new javax.swing.JButton();
        transactions = new javax.swing.JButton();
        suites = new javax.swing.JButton();
        home = new javax.swing.JButton();
        register = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        P_suites.setBackground(new java.awt.Color(102, 0, 0));

        jLabel2.setBackground(new java.awt.Color(102, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SUITES");
        P_suites.add(jLabel2);

        add(P_suites);
        P_suites.setBounds(840, 20, 60, 26);
        add(firstname);
        firstname.setBounds(203, 200, 170, 22);
        add(lastname);
        lastname.setBounds(203, 253, 170, 22);
        add(phone);
        phone.setBounds(203, 305, 170, 22);
        add(CI);
        CI.setBounds(203, 357, 170, 22);
        add(email);
        email.setBounds(678, 148, 170, 22);

        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });
        add(location);
        location.setBounds(683, 201, 170, 22);
        add(age);
        age.setBounds(683, 253, 170, 22);
        add(birthday);
        birthday.setBounds(683, 305, 170, 22);
        add(residence);
        residence.setBounds(683, 358, 170, 22);
        add(CO);
        CO.setBounds(203, 410, 170, 22);
        add(suite);
        suite.setBounds(203, 148, 170, 22);

        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back);
        back.setBounds(40, 460, 110, 30);

        proceed.setBorderPainted(false);
        proceed.setContentAreaFilled(false);
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });
        add(proceed);
        proceed.setBounds(150, 460, 110, 30);

        users.setBorderPainted(false);
        users.setContentAreaFilled(false);
        users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersActionPerformed(evt);
            }
        });
        add(users);
        users.setBounds(610, 20, 70, 30);

        guests.setBorderPainted(false);
        guests.setContentAreaFilled(false);
        guests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestsActionPerformed(evt);
            }
        });
        add(guests);
        guests.setBounds(680, 20, 70, 30);

        transactions.setBorderPainted(false);
        transactions.setContentAreaFilled(false);
        transactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsActionPerformed(evt);
            }
        });
        add(transactions);
        transactions.setBounds(770, 20, 70, 30);

        suites.setBorderPainted(false);
        suites.setContentAreaFilled(false);
        suites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suitesActionPerformed(evt);
            }
        });
        add(suites);
        suites.setBounds(840, 20, 70, 30);

        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        add(home);
        home.setBounds(900, 20, 60, 30);

        register.setBorderPainted(false);
        register.setContentAreaFilled(false);
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        add(register);
        register.setBounds(540, 20, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/room info.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        frame.setContentPane(new Register(frame));
        frame.revalidate();
    }//GEN-LAST:event_registerActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        frame.setContentPane(new Dashboard(frame));
        frame.revalidate();
    }//GEN-LAST:event_homeActionPerformed

    private void guestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestsActionPerformed
        frame.setContentPane(new GuestList(frame));
        frame.revalidate();
    }//GEN-LAST:event_guestsActionPerformed

    private void transactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsActionPerformed
        frame.setContentPane(new Transactions(frame));
        frame.revalidate();
    }//GEN-LAST:event_transactionsActionPerformed

    private void suitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suitesActionPerformed
        frame.setContentPane(new Suites(frame));
        frame.revalidate();
    }//GEN-LAST:event_suitesActionPerformed

    private void usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersActionPerformed
        frame.setContentPane(new UserList(frame));
        frame.revalidate();
    }//GEN-LAST:event_usersActionPerformed

    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
  
        int Age = Integer.parseInt(age.getText().toString());
        frame.setContentPane(new payment_info(frame, roomNumber, firstname.getText(), lastname.getText(),
        phone.getText(), CI.getText(), CO.getText(), email.getText(), location.getText(),
        Age, birthday.getText(), residence.getText(), roomType, rate, details, backp));
        frame.revalidate();
    }//GEN-LAST:event_proceedActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        frame.setContentPane(backp);
        frame.revalidate();
    }//GEN-LAST:event_backActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CI;
    private javax.swing.JTextField CO;
    private javax.swing.JPanel P_suites;
    private javax.swing.JTextField age;
    private javax.swing.JButton back;
    private javax.swing.JTextField birthday;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton guests;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField location;
    private javax.swing.JTextField phone;
    private javax.swing.JButton proceed;
    private javax.swing.JButton register;
    private javax.swing.JTextField residence;
    private javax.swing.JTextField suite;
    private javax.swing.JButton suites;
    private javax.swing.JButton transactions;
    private javax.swing.JButton users;
    // End of variables declaration//GEN-END:variables
}
