/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SRC;

/**
 *
 * @author reyes
 */
public class UserList extends javax.swing.JPanel {

    private SRC.NewJFrame frame;
    public UserList(SRC.NewJFrame frame) {
        this.frame = frame;
        initComponents();
        
        fetch();
    }
    
        public void fetch() {

         try {

             // MYSQL CONNECTION
             Class.forName("com.mysql.cj.jdbc.Driver");

             java.sql.Connection con = java.sql.DriverManager.getConnection(
                     "jdbc:mysql://localhost:3306/hms",
                     "root",
                     ""
             );

             // SQL QUERY
             String sql = "SELECT * FROM employee";

             java.sql.PreparedStatement ps = con.prepareStatement(sql);

             java.sql.ResultSet rs = ps.executeQuery();

             // TABLE MODEL
             javax.swing.table.DefaultTableModel model =
                     (javax.swing.table.DefaultTableModel) userTable.getModel();

             // CLEAR OLD ROWS
             model.setRowCount(0);

             // FETCH DATA
             while (rs.next()) {

                 String employee_id = rs.getString("employee_id");
                 String first_name = rs.getString("first_name");
                 String last_name = rs.getString("last_name");
                 String account_number = rs.getString("account_number");
                 String role = rs.getString("role");
                 String status = rs.getString("status");
                 String gender = rs.getString("gender");
                 String age = rs.getString("age");
                 String birthdate = rs.getString("birthdate");
                 String email = rs.getString("email");
                 String phone_number = rs.getString("phone_number");

                 // ADD ROW TO JTABLE
                 model.addRow(new Object[]{
                     employee_id,
                     first_name,
                     last_name,
                     account_number,
                     role,
                     status,
                     gender,
                     age,
                     birthdate,
                     email,
                     phone_number
                 });
             }

             rs.close();
             ps.close();
             con.close();

         } catch (Exception e) {
             e.printStackTrace();
         }
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_suites = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        users = new javax.swing.JButton();
        guests = new javax.swing.JButton();
        transactions = new javax.swing.JButton();
        suites = new javax.swing.JButton();
        home = new javax.swing.JButton();
        register = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        P_suites.setBackground(new java.awt.Color(102, 0, 0));

        jLabel2.setBackground(new java.awt.Color(102, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USER LIST");
        P_suites.add(jLabel2);

        add(P_suites);
        P_suites.setBounds(610, 20, 70, 30);

        userTable.setBackground(new java.awt.Color(204, 204, 204));
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Firstname", "Lastname", "Account number", "Role", "Status", "Gender", "Age", "Birthday", "Email", "Phone number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(80, 180, 800, 290);

        users.setBorderPainted(false);
        users.setContentAreaFilled(false);
        users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersActionPerformed(evt);
            }
        });
        add(users);
        users.setBounds(610, 20, 70, 30);

        guests.setBorderPainted(false);
        guests.setContentAreaFilled(false);
        guests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestsActionPerformed(evt);
            }
        });
        add(guests);
        guests.setBounds(680, 20, 70, 30);

        transactions.setBorderPainted(false);
        transactions.setContentAreaFilled(false);
        transactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsActionPerformed(evt);
            }
        });
        add(transactions);
        transactions.setBounds(770, 20, 70, 30);

        suites.setBorderPainted(false);
        suites.setContentAreaFilled(false);
        suites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suitesActionPerformed(evt);
            }
        });
        add(suites);
        suites.setBounds(840, 20, 70, 30);

        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        add(home);
        home.setBounds(900, 20, 60, 30);

        register.setBorderPainted(false);
        register.setContentAreaFilled(false);
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        add(register);
        register.setBounds(540, 20, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/USERS LIST.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        frame.setContentPane(new Register(frame));
        frame.revalidate();
    }//GEN-LAST:event_registerActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        frame.setContentPane(new Dashboard(frame));
        frame.revalidate();
    }//GEN-LAST:event_homeActionPerformed

    private void guestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestsActionPerformed
        frame.setContentPane(new GuestList(frame));
        frame.revalidate();
    }//GEN-LAST:event_guestsActionPerformed

    private void transactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsActionPerformed
        frame.setContentPane(new Transactions(frame));
        frame.revalidate();
    }//GEN-LAST:event_transactionsActionPerformed

    private void suitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suitesActionPerformed
        frame.setContentPane(new Suites(frame));
        frame.revalidate();
    }//GEN-LAST:event_suitesActionPerformed

    private void usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersActionPerformed
        frame.setContentPane(new UserList(frame));
        frame.revalidate();
    }//GEN-LAST:event_usersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P_suites;
    private javax.swing.JButton guests;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton register;
    private javax.swing.JButton suites;
    private javax.swing.JButton transactions;
    private javax.swing.JTable userTable;
    private javax.swing.JButton users;
    // End of variables declaration//GEN-END:variables
}
